/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.cleankod;

import static org.assertj.core.api.Assertions.assertThat;

import org.testng.annotations.Test;

import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class MemoizableSupplierTest {
    private final AtomicLong initialValue = new AtomicLong(0L);
    private final MemoizableSupplier<Long> supplier = new MemoizableSupplier<>(initialValue::getAndIncrement);

    @Test
    public void shouldReturnMemoizedValue() {
        var numbers = List.of(
            supplier.get(),
            supplier.get(),
            supplier.get(),
            supplier.get()
        );

        assertThat(numbers).containsOnly(0L);
    }
}
